In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [47]:
path = '/content/drive/MyDrive/Datasets_practice/'
data = pd.read_csv(path+"2015-building-energy-benchmarking.csv")

In [18]:
data1 = data

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3340 entries, 0 to 3339
Data columns (total 47 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   OSEBuildingID                                                  3340 non-null   int64
 1   DataYear                                                       3340 non-null   int64
 2   BuildingType                                                   3340 non-null   object
 3   PrimaryPropertyType                                            3340 non-null   object
 4   PropertyName                                                   3340 non-null   object
 5   TaxParcelIdentificationNumber                                  3338 non-null   object
 6   Location                                                       3340 non-null   object
 7   CouncilDistrictCode                                            3340 non-null   int64
 8   Neighborhood                                                   3340 non-null   object
 9   YearBuilt                                                      3340 non-null   int64
 10  NumberofBuildings                                              3340 non-null   int64
 11  NumberofFloors                                                 3332 non-null   float64
 12  PropertyGFATotal                                               3340 non-null   int64
 13  PropertyGFAParking                                             3340 non-null   int64
 14  PropertyGFABuilding(s)                                         3340 non-null   int64
 15  ListOfAllPropertyUseTypes                                      3213 non-null   object
 16  LargestPropertyUseType                                         3204 non-null   object
 17  LargestPropertyUseTypeGFA                                      3204 non-null   float64
 18  SecondLargestPropertyUseType                                   1559 non-null   object
 19  SecondLargestPropertyUseTypeGFA                                1559 non-null   float64
 20  ThirdLargestPropertyUseType                                    560 non-null    object
 21  ThirdLargestPropertyUseTypeGFA                                 560 non-null    float64
 22  YearsENERGYSTARCertified                                       110 non-null    object
 23  ENERGYSTARScore                                                2560 non-null   float64
 24  SiteEUI(kBtu/sf)                                               3330 non-null   float64
 25  SiteEUIWN(kBtu/sf)                                             3330 non-null   float64
 26  SourceEUI(kBtu/sf)                                             3330 non-null   float64
 27  SourceEUIWN(kBtu/sf)                                           3330 non-null   float64
 28  SiteEnergyUse(kBtu)                                            3330 non-null   float64
 29  SiteEnergyUseWN(kBtu)                                          3330 non-null   float64
 30  SteamUse(kBtu)                                                 3330 non-null   float64
 31  Electricity(kWh)                                               3330 non-null   float64
 32  Electricity(kBtu)                                              3330 non-null   float64
 33  NaturalGas(therms)                                             3330 non-null   float64
 34  NaturalGas(kBtu)                                               3330 non-null   float64
 35  OtherFuelUse(kBtu)                                             3330 non-null   float64
 36  GHGEmissions(MetricTonsCO2e)                                   3330 non-null   float64
 37  GHGEmissionsIntensity(kgCO2e/ft2)                              3330 non-null   float64
 38  DefaultData                                                    3339 non-null   object
 39  Comment                                                        13 non-null     object
 40  ComplianceStatus                                               3340 non-null   object
 41  Outlier                                                        84 non-null     object
 42  2010 Census Tracts                                             224 non-null    float64
 43  Seattle Police Department Micro Community Policing Plan Areas  3338 non-null   float64
 44  City Council Districts                                         213 non-null    float64
 45  SPD Beats                                                      3338 non-null   float64
 46  Zip Codes                                                      3340 non-null   int64
dtypes: float64(23), int64(9), object(15)
memory usage: 1.2+ MB

In [20]:
data

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,TaxParcelIdentificationNumber,Location,CouncilDistrictCode,Neighborhood,YearBuilt,...,GHGEmissionsIntensity(kgCO2e/ft2),DefaultData,Comment,ComplianceStatus,Outlier,2010 Census Tracts,Seattle Police Department Micro Community Policing Plan Areas,City Council Districts,SPD Beats,Zip Codes
0,1,2015,NonResidential,Hotel,MAYFLOWER PARK HOTEL,659000030,"{'latitude': '47.61219025', 'longitude': '-122...",7,DOWNTOWN,1927,...,2.64,No,NaN,Compliant,NaN,NaN,14.0,NaN,31.0,18081
1,2,2015,NonResidential,Hotel,PARAMOUNT HOTEL,659000220,"{'latitude': '47.61310583', 'longitude': '-122...",7,DOWNTOWN,1996,...,2.38,No,NaN,Compliant,NaN,NaN,14.0,NaN,31.0,18081
2,3,2015,NonResidential,Hotel,WESTIN HOTEL,659000475,"{'latitude': '47.61334897', 'longitude': '-122...",7,DOWNTOWN,1969,...,1.92,Yes,NaN,Compliant,NaN,NaN,56.0,NaN,31.0,18081
3,5,2015,NonResidential,Hotel,HOTEL MAX,659000640,"{'latitude': '47.61421585', 'longitude': '-122...",7,DOWNTOWN,1926,...,31.38,No,NaN,Compliant,High Outlier,NaN,56.0,NaN,31.0,18081
4,8,2015,NonResidential,Hotel,WARWICK SEATTLE HOTEL,659000970,"{'latitude': '47.6137544', 'longitude': '-122....",7,DOWNTOWN,1980,...,4.02,No,NaN,Compliant,NaN,NaN,56.0,NaN,31.0,19576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3335,50049,2015,Multifamily LR (1-4),Low-Rise Multifamily,PACIFIC CENTER CONDOMINIUM,6599950000,"{'latitude': '47.59950256', 'longitude': '-122...",2,DOWNTOWN,2000,...,0.07,No,NaN,Compliant,NaN,NaN,26.0,NaN,16.0,18379
3336,50055,2015,Multifamily MR (5-9),Mid-Rise Multifamily,IDENTITY APTS 4123,1142001670,"{'latitude': '47.65752471', 'longitude': '-122...",4,NORTHEAST,2014,...,0.61,No,NaN,Compliant,NaN,NaN,60.0,NaN,38.0,18383
3337,50057,2015,Multifamily HR (10+),High-Rise Multifamily,CIRRUS,660000575,"{'latitude': '47.61649845', 'longitude': '-122...",7,DOWNTOWN,2015,...,1.89,No,NaN,Compliant,NaN,NaN,56.0,NaN,7.0,19576
3338,50058,2015,Multifamily LR (1-4),Low-Rise Multifamily,WEDGEWOOD ESTATES BLDG A,6392001040,"{'latitude': '47.68396954', 'longitude': '-122...",4,NORTHEAST,1981,...,0.04,No,NaN,Compliant,NaN,NaN,55.0,NaN,48.0,18792
3339,50059,2015,Multifamily LR (1-4),Low-Rise Multifamily,WEDGEWOOD ESTATES BLDG B,6392001040,"{'latitude': '47.68396954', 'longitude': '-122...",4,NORTHEAST,1981,...,0.05,No,NaN,Compliant,NaN,NaN,55.0,NaN,48.0,18792

In [21]:
data.describe()

,OSEBuildingID,DataYear,CouncilDistrictCode,YearBuilt,NumberofBuildings,NumberofFloors,PropertyGFATotal,PropertyGFAParking,PropertyGFABuilding(s),LargestPropertyUseTypeGFA,...,NaturalGas(therms),NaturalGas(kBtu),OtherFuelUse(kBtu),GHGEmissions(MetricTonsCO2e),GHGEmissionsIntensity(kgCO2e/ft2),2010 Census Tracts,Seattle Police Department Micro Community Policing Plan Areas,City Council Districts,SPD Beats,Zip Codes
count,3340.000000,3340.0,3340.000000,3340.000000,3340.000000,3332.000000,3.340000e+03,3340.000000,3.340000e+03,3.204000e+03,...,3.330000e+03,3.330000e+03,3.330000e+03,3330.000000,3330.000000,224.000000,3338.000000,213.000000,3338.000000,3340.000000
mean,20522.168263,2015.0,4.450898,1967.624850,1.035629,4.682173,9.077289e+04,11054.032335,7.971886e+04,7.488154e+04,...,1.253304e+04,1.253304e+06,7.142301e+03,110.094102,0.985339,123.062500,32.380168,1.347418,24.825644,18786.680240
std,11511.515874,0.0,2.127203,32.949847,0.784463,5.458460,1.493058e+05,35296.330507,1.292314e+05,1.236249e+05,...,4.415142e+04,4.415142e+06,1.962790e+05,409.450179,1.637172,5.812128,19.907567,0.477272,15.006287,588.604192
min,1.000000,2015.0,1.000000,1900.000000,1.000000,0.000000,2.000000e+04,-3.000000,-5.055000e+04,5.872000e+03,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,116.000000,1.000000,1.000000,1.000000,17916.000000
25%,19921.750000,2015.0,3.000000,1947.000000,1.000000,2.000000,2.848700e+04,0.000000,2.668300e+04,2.500000e+04,...,0.000000e+00,0.000000e+00,0.000000e+00,9.265000,0.080000,117.000000,14.000000,1.000000,10.000000,18379.000000
50%,22977.000000,2015.0,4.000000,1973.000000,1.000000,4.000000,4.385500e+04,0.000000,4.132600e+04,3.900000e+04,...,2.945500e+03,2.945770e+05,0.000000e+00,32.740000,0.460000,123.000000,33.000000,1.000000,26.000000,18390.000000
75%,25748.000000,2015.0,7.000000,1996.000000,1.000000,5.000000,8.842800e+04,4304.250000,7.872600e+04,7.206750e+04,...,1.115325e+04,1.115366e+06,0.000000e+00,88.642500,1.180000,125.500000,50.000000,2.000000,38.000000,19576.000000
max,50059.000000,2015.0,7.000000,2015.000000,39.000000,99.000000,2.200000e+06,512608.000000,2.200000e+06,1.719643e+06,...,1.364484e+06,1.364484e+08,8.269669e+06,11824.890000,31.380000,135.000000,61.000000,2.000000,51.000000,19584.000000

In [48]:
# delete col nans
data = data.replace([np.inf, -np.inf], np.nan)
series = data.isna().sum(axis = 0)/len(data)
col_to_drop = []

for index, value in series.items():
  if value >0.7:
    col_to_drop.append(index)

print(col_to_drop)

['ThirdLargestPropertyUseType', 'ThirdLargestPropertyUseTypeGFA', 'YearsENERGYSTARCertified', 'Comment', 'Outlier', '2010 Census Tracts', 'City Council Districts']

In [49]:
data = data.drop(columns = col_to_drop)

data =  data.dropna()

In [50]:
data.drop('Location', axis=1, inplace=True)

# Identify numerical and categorical columns
numerical_columns = data.select_dtypes(include='number').columns
categorical_columns = data.select_dtypes(include='object').columns

# Replace NaN values in numerical columns
data[numerical_columns] = data[numerical_columns].fillna(data[numerical_columns].mean())

# Replace NaN values in categorical columns
data[categorical_columns] = data[categorical_columns].fillna(data[categorical_columns].mode().iloc[0])

In [51]:

#remove outliers
'''
column_name = 'feature_data'
z_scores = np.abs((data[column_name] - data[column_name].mean()) / data[column_name].std())
threshold = 3
filtered_df = data[z_scores < threshold]
'''

"\ncolumn_name = 'feature_data'\nz_scores = np.abs((data[column_name] - data[column_name].mean()) / data[column_name].std())\nthreshold = 3\nfiltered_df = data[z_scores < threshold]\n"

In [ ]:
# check for outliers
import seaborn as sns
for col in numerical_columns:
  sns.boxplot(data = data, x = col  )
  plt.show()

In [27]:
#Check
print(sum(data.isna().sum(axis = 1)))
print(sum(data.isna().sum(axis = 0)))

0
0

In [28]:
data.columns

Index(['OSEBuildingID', 'DataYear', 'BuildingType', 'PrimaryPropertyType',
       'PropertyName', 'TaxParcelIdentificationNumber', 'CouncilDistrictCode',
       'Neighborhood', 'YearBuilt', 'NumberofBuildings', 'NumberofFloors',
       'PropertyGFATotal', 'PropertyGFAParking', 'PropertyGFABuilding(s)',
       'ListOfAllPropertyUseTypes', 'LargestPropertyUseType',
       'LargestPropertyUseTypeGFA', 'SecondLargestPropertyUseType',
       'SecondLargestPropertyUseTypeGFA', 'ENERGYSTARScore',
       'SiteEUI(kBtu/sf)', 'SiteEUIWN(kBtu/sf)', 'SourceEUI(kBtu/sf)',
       'SourceEUIWN(kBtu/sf)', 'SiteEnergyUse(kBtu)', 'SiteEnergyUseWN(kBtu)',
       'SteamUse(kBtu)', 'Electricity(kWh)', 'Electricity(kBtu)',
       'NaturalGas(therms)', 'NaturalGas(kBtu)', 'OtherFuelUse(kBtu)',
       'GHGEmissions(MetricTonsCO2e)', 'GHGEmissionsIntensity(kgCO2e/ft2)',
       'DefaultData', 'ComplianceStatus',
       'Seattle Police Department Micro Community Policing Plan Areas',
       'SPD Beats', 'Zip Codes'],
      dtype='object')

In [52]:


# Split the data into training and testing sets
X = data.drop(['GHGEmissionsIntensity(kgCO2e/ft2)','GHGEmissions(MetricTonsCO2e)' ], axis=1)
y = data['GHGEmissionsIntensity(kgCO2e/ft2)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [53]:

### CAREFUL: remove the target from the preprocessing !!!!

numerical_columns = list(numerical_columns)
numerical_columns.remove('GHGEmissionsIntensity(kgCO2e/ft2)')
numerical_columns.remove('GHGEmissions(MetricTonsCO2e)')

In [54]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

# Create the column transformer for preprocessing
preprocess = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore'), categorical_columns),  # Apply Onehot encoding features
    (StandardScaler(), numerical_columns)  # Apply StandardScaler to numerical features
)


# Fit and transform the training data
X_train = preprocess.fit_transform(X_train)

# Transform the test data using the fitted transformer
X_test = preprocess.transform(X_test)

In [55]:
##


# Assuming 'df' is your DataFrame and 'target_variable' is the name of your target variable column
target_variable = 'GHGEmissions(MetricTonsCO2e)'  # Replace with the name of your target variable

# Calculate the skewness of each feature with respect to the target variable
skewness = data.drop(target_variable, axis=1).skew().sort_values(ascending=False, key=abs)

# Print the skewness values
print(skewness)

NumberofBuildings                                                25.313673
OtherFuelUse(kBtu)                                               23.041116
SteamUse(kBtu)                                                   20.263932
NaturalGas(kBtu)                                                 11.077469
NaturalGas(therms)                                               11.077465
Electricity(kWh)                                                 11.075797
Electricity(kBtu)                                                11.075797
SiteEnergyUseWN(kBtu)                                            10.284538
SiteEnergyUse(kBtu)                                              10.254847
SourceEUI(kBtu/sf)                                                8.334229
SourceEUIWN(kBtu/sf)                                              8.306931
SiteEUI(kBtu/sf)                                                  6.112707
SiteEUIWN(kBtu/sf)                                                5.801948
LargestPropertyUseTypeGFA                                         4.562153
PropertyGFABuilding(s)                                            4.425724
PropertyGFAParking                                                4.257124
PropertyGFATotal                                                  4.183761
NumberofFloors                                                    3.796949
SecondLargestPropertyUseTypeGFA                                   3.704938
GHGEmissionsIntensity(kgCO2e/ft2)                                 3.348681
ENERGYSTARScore                                                  -0.958746
YearBuilt                                                        -0.885523
Zip Codes                                                         0.438907
CouncilDistrictCode                                              -0.317071
SPD Beats                                                         0.170917
OSEBuildingID                                                     0.097728
Seattle Police Department Micro Community Policing Plan Areas    -0.017680
DataYear                                                          0.000000
dtype: float64

<ipython-input-55-43ac57df1f7a>:8: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  skewness = data.drop(target_variable, axis=1).skew().sort_values(ascending=False, key=abs)

In [56]:
skewed_vars = skewness.where(skewness > 0.5)
skewed_vars= skewed_vars.dropna()
data[skewed_vars.index] = np.log1p(data[skewed_vars.index])

/usr/local/lib/python3.10/dist-packages/pandas/core/internals/blocks.py:351: RuntimeWarning: invalid value encountered in log1p
  result = func(self.values, **kwargs)

In [57]:

data.dropna(axis = 0, inplace = True)

In [58]:
# Split the data into training and testing sets
X = data.drop(['GHGEmissionsIntensity(kgCO2e/ft2)','GHGEmissions(MetricTonsCO2e)' ], axis=1)
y = data['GHGEmissionsIntensity(kgCO2e/ft2)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
for column in X.columns:
    plt.scatter(X[column], y)
    plt.xlabel(column)
    plt.ylabel('Dependent Variable')
    plt.show()

In [59]:


from sklearn.compose import make_column_transformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

# Create the column transformer for preprocessing
preprocess = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore'), categorical_columns),  # Apply Onehot encoding features
    (StandardScaler(), numerical_columns)  # Apply StandardScaler to numerical features
)


# Fit and transform the training data
X_train = preprocess.fit_transform(X_train)

# Transform the test data using the fitted transformer
X_test = preprocess.transform(X_test)

In [60]:

import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, accuracy_score



lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_predictions = lr_model.predict(X_test)
lr_mse = mean_squared_error(y_test, lr_predictions)
lr_mae = mean_absolute_error(y_test, lr_predictions)
lr_r2 = r2_score(y_test, lr_predictions)


# Ridge Regression
ridge_model = Ridge(alpha=0.5)
ridge_model.fit(X_train, y_train)
ridge_predictions = ridge_model.predict(X_test)
ridge_mse = mean_squared_error(y_test, ridge_predictions)
ridge_mae = mean_absolute_error(y_test, ridge_predictions)
ridge_r2 = r2_score(y_test, ridge_predictions)

# Lasso Regression
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(X_train, y_train)
lasso_predictions = lasso_model.predict(X_test)
lasso_mse = mean_squared_error(y_test, lasso_predictions)
lasso_mae = mean_absolute_error(y_test, lasso_predictions)
lasso_r2 = r2_score(y_test, lasso_predictions)

# Decision Tree Regression
dt_model = DecisionTreeRegressor()
dt_model.fit(X_train, y_train)
dt_predictions = dt_model.predict(X_test)
dt_mse = mean_squared_error(y_test, dt_predictions)
dt_mae = mean_absolute_error(y_test, dt_predictions)
dt_r2 = r2_score(y_test, dt_predictions)

# Random Forest Regression
rf_model = RandomForestRegressor(n_estimators=100)
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)
rf_mse = mean_squared_error(y_test, rf_predictions)
rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_r2 = r2_score(y_test, rf_predictions)

# Gradient Boosting Regression
gb_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1)
gb_model.fit(X_train, y_train)
gb_predictions = gb_model.predict(X_test)
gb_mse = mean_squared_error(y_test, gb_predictions)
gb_mae = mean_absolute_error(y_test, gb_predictions)
gb_r2 = r2_score(y_test, gb_predictions)

# Print the evaluation metrics for each model
print("Linear Regression:")
print("MSE:", lr_mse)
print("MAE:", lr_mae)
print("R2 Score:", lr_r2)
print()
print("Ridge Regression:")
print("MSE:", ridge_mse)
print("MAE:", ridge_mae)
print("R2 Score:", ridge_r2)
print()
print("Lasso Regression:")
print("MSE:", lasso_mse)
print("MAE:", lasso_mae)
print("R2 Score:", lasso_r2)
print()
print("Decision Tree Regression:")
print("MSE:", dt_mse)
print("MAE:", dt_mae)
print("R2 Score:", dt_r2)
print()
print("Random Forest Regression:")
print("MSE:", rf_mse)
print("MAE:", rf_mae)
print("R2 Score:", rf_r2)
print()
print("Gradient Boosting Regression:")
print("MSE:", gb_mse)
print("MAE:", gb_mae)
print("R2 Score:", gb_r2)

Linear Regression:
MSE: 0.01478047839232243
MAE: 0.08327432715016794
R2 Score: 0.9315760674560509

Ridge Regression:
MSE: 0.014742561906461261
MAE: 0.08353964965173065
R2 Score: 0.9317515959472137

Lasso Regression:
MSE: 0.08454270831449386
MAE: 0.216238867644791
R2 Score: 0.6086226428368844

Decision Tree Regression:
MSE: 0.039397610498911814
MAE: 0.10532502029062386
R2 Score: 0.8176148720212876

Random Forest Regression:
MSE: 0.014618577803061125
MAE: 0.06325810564937533
R2 Score: 0.9323255611263097

Gradient Boosting Regression:
MSE: 0.013555082452017034
MAE: 0.06943877010215538
R2 Score: 0.9372488479259062

- Mean Squared Error (MSE): It measures the average squared difference between the predicted and actual values. A lower MSE indicates better model performance, with a value of 0 indicating a perfect fit.

- Mean Absolute Error (MAE): It measures the average absolute difference between the predicted and actual values. Like MSE, a lower MAE suggests better model performance. MAE is less sensitive to outliers compared to MSE.

- R-squared Score: Also known as the coefficient of determination, it represents the proportion of the variance in the dependent variable that can be explained by the independent variables. R-squared ranges from 0 to 1, with a higher value indicating a better fit. A score of 1 means the model explains all the variance, while a score of 0 means the model provides no improvement over a constant mean.

## With Grid Search

In [62]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

# Define the parameter grid for each model
lr_params = {}
ridge_params = {'alpha': [0.1, 0.5, 1.0]}
lasso_params = {'alpha': [0.1, 0.5, 1.0]}
dt_params = {'max_depth': [None, 5, 10], 'min_samples_split': [2, 5, 10]}
rf_params = {'n_estimators': [100, 200, 500], 'max_depth': [None, 5, 10]}
gb_params = {'n_estimators': [100, 200, 500], 'learning_rate': [0.1, 0.01, 0.001]}

# Perform grid search for each model
lr_grid = GridSearchCV(LinearRegression(), lr_params, cv=5)
ridge_grid = GridSearchCV(Ridge(), ridge_params, cv=5)
lasso_grid = GridSearchCV(Lasso(), lasso_params, cv=5)
dt_grid = GridSearchCV(DecisionTreeRegressor(), dt_params, cv=5)
rf_grid = GridSearchCV(RandomForestRegressor(), rf_params, cv=5)
gb_grid = GridSearchCV(GradientBoostingRegressor(), gb_params, cv=5)

# Fit the models with grid search
lr_grid.fit(X_train, y_train)
ridge_grid.fit(X_train, y_train)
lasso_grid.fit(X_train, y_train)
dt_grid.fit(X_train, y_train)
rf_grid.fit(X_train, y_train)
gb_grid.fit(X_train, y_train)

# Get the best models and their predictions
lr_best_model = lr_grid.best_estimator_
lr_predictions = lr_best_model.predict(X_test)

ridge_best_model = ridge_grid.best_estimator_
ridge_predictions = ridge_best_model.predict(X_test)

lasso_best_model = lasso_grid.best_estimator_
lasso_predictions = lasso_best_model.predict(X_test)

dt_best_model = dt_grid.best_estimator_
dt_predictions = dt_best_model.predict(X_test)

rf_best_model = rf_grid.best_estimator_
rf_predictions = rf_best_model.predict(X_test)

gb_best_model = gb_grid.best_estimator_
gb_predictions = gb_best_model.predict(X_test)

# Calculate evaluation metrics
lr_mse = mean_squared_error(y_test, lr_predictions)
lr_mae = mean_absolute_error(y_test, lr_predictions)
lr_r2 = r2_score(y_test, lr_predictions)

ridge_mse = mean_squared_error(y_test, ridge_predictions)
ridge_mae = mean_absolute_error(y_test, ridge_predictions)
ridge_r2 = r2_score(y_test, ridge_predictions)

lasso_mse = mean_squared_error(y_test, lasso_predictions)
lasso_mae = mean_absolute_error(y_test, lasso_predictions)
lasso_r2 = r2_score(y_test, lasso_predictions)

dt_mse = mean_squared_error(y_test, dt_predictions)
dt_mae = mean_absolute_error(y_test, dt_predictions)
dt_r2 = r2_score(y_test, dt_predictions)

rf_mse = mean_squared_error(y_test, rf_predictions)
rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_r2 = r2_score(y_test, rf_predictions)

gb_mse = mean_squared_error(y_test, gb_predictions)
gb_mae = mean_absolute_error(y_test, gb_predictions)
gb_r2 = r2_score(y_test, gb_predictions)

# Print the evaluation metrics for each model
print("Linear Regression:")
print("MSE:", lr_mse)
print("MAE:", lr_mae)
print("R2 Score:", lr_r2)
print()
print("Ridge Regression:")
print("MSE:", ridge_mse)
print("MAE:", ridge_mae)
print("R2 Score:", ridge_r2)
print()
print("Lasso Regression:")
print("MSE:", lasso_mse)
print("MAE:", lasso_mae)
print("R2 Score:", lasso_r2)
print()
print("Decision Tree Regression:")
print("MSE:", dt_mse)
print("MAE:", dt_mae)
print("R2 Score:", dt_r2)
print()
print("Random Forest Regression:")
print("MSE:", rf_mse)
print("MAE:", rf_mae)
print("R2 Score:", rf_r2)
print()
print("Gradient Boosting Regression:")
print("MSE:", gb_mse)
print("MAE:", gb_mae)
print("R2 Score:", gb_r2)

Linear Regression:
MSE: 0.01478047839232243
MAE: 0.08327432715016794
R2 Score: 0.9315760674560509

Ridge Regression:
MSE: 0.01476610069390506
MAE: 0.08332288124349674
R2 Score: 0.9316426267811644

Lasso Regression:
MSE: 0.08454270831449386
MAE: 0.216238867644791
R2 Score: 0.6086226428368844

Decision Tree Regression:
MSE: 0.03634981451503658
MAE: 0.10227117016257097
R2 Score: 0.8317241708729893

Random Forest Regression:
MSE: 0.01421633226593485
MAE: 0.06312331750564627
R2 Score: 0.9341876944597428

Gradient Boosting Regression:
MSE: 0.011207953531294694
MAE: 0.060441154707538254
R2 Score: 0.9481145172689824

In [ ]:
for column in X.columns:
    plt.scatter(X[column], y)
    plt.xlabel(column)
    plt.ylabel('Dependent Variable')
    plt.show()

In [ ]:
correlations = X.corrwith(y)
print("Pearson Correlation Coefficients:")
print(correlations)

In [ ]:
X.columns

## Transform to Classification

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split


# Split the data into training and testing sets
X = data.drop(['GHGEmissionsIntensity(kgCO2e/ft2)','GHGEmissions(MetricTonsCO2e)' ], axis=1)
y = data['GHGEmissionsIntensity(kgCO2e/ft2)']


# pd.cut divides equally and pd.qcut divides frequency

#pd.qcut(y, q = 5, labels=False, retbins=True). #to see the frequency

#y_classification = pd.cut(y, bins = 5)
y_classification = pd.qcut(y, q = 5)


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_classification, test_size=0.2, random_state=42)

# Train a classification model
#model = LogisticRegression()
#model.fit(X_train, y_train)

In [ ]:
import seaborn as sns

sns.countplot(data = data, x = y_classification)

In [ ]:
from sklearn.model_selection import GridSearchCV


logreg = LogisticRegression()
dtree = DecisionTreeClassifier()
rf = RandomForestClassifier()


logreg_params = {'C': [0.1, 1, 10]}
dtree_params = {'max_depth': [None, 5, 10], 'min_samples_split': [2, 5, 10]}
rf_params = {'n_estimators': [100, 200, 300], 'max_depth': [None, 5, 10]}

# Perform hyperparameter tuning using GridSearchCV
logreg_grid = GridSearchCV(logreg, logreg_params, cv=5)
logreg_grid.fit(X_dev, y_train)

dtree_grid = GridSearchCV(dtree, dtree_params, cv=5)
dtree_grid.fit(X_dev, y_train)

rf_grid = GridSearchCV(rf, rf_params, cv=5)
rf_grid.fit(X_dev, y_train)

# Print the best hyperparameters and evaluation scores
print("Logistic Regression:")
print("Best Hyperparameters:", logreg_grid.best_params_)
print("Cross-validation Score:", logreg_grid.best_score_)

print("Decision Tree:")
print("Best Hyperparameters:", dtree_grid.best_params_)
print("Cross-validation Score:", dtree_grid.best_score_)

print("Random Forest:")
print("Best Hyperparameters:", rf_grid.best_params_)
print("Cross-validation Score:", rf_grid.best_score_)

# Select the best-performing model based on the evaluation results
best_model = rf_grid.best_estimator_
best_model.fit(X_train, y_train)

# Evaluate the best model on the test set
accuracy = best_model.score(X_test, y_test)
print("Test Accuracy:", accuracy)